//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloAero.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Russian {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Russian() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelloAero.Languages.Russian", typeof(Russian).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Composite.
        /// </summary>
        public static string Composite {
            get {
                return ResourceManager.GetString("Composite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grid.Resources&gt;
        ///    &lt;BooleanConverter x:Key=&quot;YesNoConverter&quot; OnTrue=&quot;Yes&quot; OnFalse=&quot;No&quot;/&gt;
        ///    &lt;SwitchConverter 
        ///        x:Key=&quot;CompositeSwitchConverter&quot;
        ///        PostConverter=&quot;{StaticResource YesNoConverter}&quot;&gt;
        ///        &lt;Case Key=&quot;0&quot; Value=&quot;False&quot;/&gt;
        ///        &lt;Case Key=&quot;1&quot; Value=&quot;True&quot;/&gt;
        ///    &lt;/SwitchConverter&gt;
        ///&lt;/Grid.Resources&gt;
        ///&lt;TextBlock Text=&quot;{Binding Number, Converter={StaticResource CompositeSwitchConverter}}&quot;/&gt;.
        /// </summary>
        public static string CompositeConverterSample {
            get {
                return ResourceManager.GetString("CompositeConverterSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конвертеры.
        /// </summary>
        public static string Converters {
            get {
                return ResourceManager.GetString("Converters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Равноправные Инжекции.
        /// </summary>
        public static string EquitableInjections {
            get {
                return ResourceManager.GetString("EquitableInjections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эвокация.
        /// </summary>
        public static string Evocators {
            get {
                return ResourceManager.GetString("Evocators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экспонирование.
        /// </summary>
        public static string Exposable {
            get {
                return ResourceManager.GetString("Exposable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girl.
        /// </summary>
        public static string Girl {
            get {
                return ResourceManager.GetString("Girl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DataContract]
        ///    public class GirlViewModel : ContextObject, IExposable
        ///    {
        ///        [DataMember]
        ///        public int Kisses
        ///        {
        ///            get { return Get(() =&gt; Kisses); }
        ///            set { Set(() =&gt; Kisses, value); }
        ///        }
        ///
        ///        public void Expose()
        ///        {
        ///            var guyViewModel = Store.Get&lt;GuyViewModel&gt;();
        ///
        ///            this[() =&gt; Kisses].PropertyChanged += (sender, args) =&gt;
        ///            {
        ///                Context.Get(&quot;KissGirl&quot;).RaiseCanExecuteChanged();
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GirlSample {
            get {
                return ResourceManager.GetString("GirlSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guy.
        /// </summary>
        public static string Guy {
            get {
                return ResourceManager.GetString("Guy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [DataContract]
        ///    public class GuyViewModel : ContextObject, IExposable
        ///    {
        ///        [DataMember]
        ///        public int Kisses
        ///        {
        ///            get { return Get(() =&gt; Kisses); }
        ///            set { Set(() =&gt; Kisses, value); }
        ///        }
        ///
        ///        public void Expose()
        ///        {
        ///            var girlViewModel = Store.Get&lt;GirlViewModel&gt;();
        ///
        ///            this[() =&gt; Kisses].PropertyChanged += (sender, args) =&gt;
        ///            {
        ///                Context.Get(&quot;KissGirl&quot;).RaiseCanExecuteChanged();
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GuySample {
            get {
                return ResourceManager.GetString("GuySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline.
        /// </summary>
        public static string Inline {
            get {
                return ResourceManager.GetString("Inline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grid.Resources&gt;
        ///    &lt;InlineConverter x:Key=&quot;InlineConverter&quot; Converting=&quot;InlineConverter_OnConverting&quot;/&gt;
        ///&lt;/Grid.Resources&gt;
        ///&lt;TextBlock Text=&quot;{Binding Number, Converter={StaticResource InlineConverter}}&quot;/&gt;
        ///
        ///// Code Behind of View
        ///private void InlineConverter_OnConverting(object sender, ConverterEventArgs e)
        ///{
        ///    e.ConvertedValue =
        ///    string.Format(&quot;Title: {0} \nDataContext:\n{1} \nConverter Value: {2}&quot;,
        ///        Title,
        ///        DataContext,
        ///        e.Value);
        ///}.
        /// </summary>
        public static string InlineConverterSample {
            get {
                return ResourceManager.GetString("InlineConverterSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Локализация.
        /// </summary>
        public static string Localizing {
            get {
                return ResourceManager.GetString("Localizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        public static string One {
            get {
                return ResourceManager.GetString("One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства и Команды.
        /// </summary>
        public static string PropertiesAndCommands {
            get {
                return ResourceManager.GetString("PropertiesAndCommands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стеллаж.
        /// </summary>
        public static string Rack {
            get {
                return ResourceManager.GetString("Rack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grid Rack.Rows=&quot;* 20\Auto * 2* */100 * *&quot; Rack.Columns=&quot;* 50\*/100 *&quot;&gt;
        ///    &lt;!--...--&gt;
        ///&lt;/Grid&gt;
        ///
        ///equals
        ///
        ///&lt;Grid&gt;
        ///    &lt;Grid.RowDefinitions&gt;
        ///        &lt;RowDefinition Height=&quot;*&quot;/&gt;
        ///        &lt;RowDefinition MinHeight=&quot;20&quot; Height=&quot;Auto&quot;/&gt;
        ///        &lt;RowDefinition Height=&quot;*&quot;/&gt;
        ///        &lt;RowDefinition Height=&quot;2*&quot;/&gt;
        ///        &lt;RowDefinition Height=&quot;*&quot; MaxHeight=&quot;100&quot;/&gt;
        ///        &lt;RowDefinition Height=&quot;*&quot;/&gt;
        ///        &lt;RowDefinition Height=&quot;*&quot;/&gt;
        ///    &lt;/Grid.RowDefinitions&gt;
        ///    
        ///    &lt;Grid.ColumnDefinitions&gt;
        ///        &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RackSample {
            get {
                return ResourceManager.GetString("RackSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Умное Состояние.
        /// </summary>
        public static string SmartState {
            get {
                return ResourceManager.GetString("SmartState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To enable this feature:
        ///
        ///1. Initialize Memory Box at startup
        ///
        ///Possible, like this at App.xaml
        ///
        ///&lt;Application
        ///    x:Class=&quot;HelloAero.App&quot;
        ///    xmlns=&quot;http://schemas.microsoft.com/winfx/2006/xaml/presentation&quot;
        ///    xmlns:x=&quot;http://schemas.microsoft.com/winfx/2006/xaml&quot;
        ///    StartupUri=&quot;Views/WelcomeView.xaml&quot;
        ///    Startup=&quot;App_OnStartup&quot;
        ///    Exit=&quot;App_OnExit&quot;&gt;
        ///    &lt;Application.Resources&gt;
        ///    
        ///    &lt;/Application.Resources&gt;
        ///&lt;/Application&gt;
        ///
        ///    public partial class App
        ///    {
        ///        private void Ap [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SmartStateSample {
            get {
                return ResourceManager.GetString("SmartStateSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch.
        /// </summary>
        public static string Switch {
            get {
                return ResourceManager.GetString("Switch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Grid.Resources&gt;
        ///    &lt;SwitchConverter x:Key=&quot;NumberSwitchConverter&quot;&gt;
        ///        &lt;Case Key=&quot;0&quot; Value=&quot;{Localizing Zero}&quot;/&gt;
        ///        &lt;Case Key=&quot;1&quot; Value=&quot;{Localizing One}&quot;/&gt;
        ///    &lt;/SwitchConverter&gt;
        ///&lt;/Grid.Resources&gt;
        ///&lt;TextBlock Text=&quot;{Binding Number, Converter={StaticResource NumberSwitchConverter}}&quot;/&gt;.
        /// </summary>
        public static string SwitchConverterSample {
            get {
                return ResourceManager.GetString("SwitchConverterSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствуем.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ноль.
        /// </summary>
        public static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
